# 03 — Huấn luyện DNN, LSTM, CNN

Ba client **UNSW + BoT + CIC**; 39 feature. CIC giữ đúng 1.000.000 mẫu thật (500.000 benign + 500.000 attack). Mọi mô hình dùng **CSV raw → Log → Z-score riêng từng client → clip [-8,8]**. Mean/std chỉ fit trên tập fit; đóng băng khi dùng validation/test. Split và nhãn được giữ nguyên. Kết quả lưu ở `runs/main/`.

Ở mỗi round FL, server gộp cập nhật của UNSW/BoT/CIC với trọng số bằng nhau 1/3 rồi dùng Adam cập nhật model toàn cục. Chính sách này giống notebook tuning 02.

In [1]:
from pathlib import Path
import os, sys, json
if os.name == 'nt':
    raise RuntimeError('Mở start_notebooks.cmd để dùng kernel WSL /opt/flids-tf.')
PROJECT = next((p for p in [Path.cwd(), *Path.cwd().parents]
                if (p/'notebook_workflow.py').is_file() and (p/'configs/tuning.json').is_file()), None)
if PROJECT is None:
    raise FileNotFoundError('Mở notebook trong FL_IDS.')
os.chdir(PROJECT)
if str(PROJECT) not in sys.path: sys.path.insert(0, str(PROJECT))
CONFIG = PROJECT/'configs/tuning.json'
from notebook_workflow import settings, budget
C = settings(CONFIG)
RUN_ROOT = PROJECT/C['run_directory']
print('Project:', PROJECT)
print('Python:', sys.executable)
print('Run:', RUN_ROOT)

Project: /mnt/c/Users/admin/Downloads/FL_IDS
Python: /opt/flids-tf/bin/python
Run: /mnt/c/Users/admin/Downloads/FL_IDS/runs/main

## Huấn luyện bằng tham số được chọn từ validation

Ba Local + Centralized + FL. Ngân sách chung: FL 15 round × 3 local epoch; Local/Centralized tối đa 45 epoch, early stopping val_loss patience 5. Áp dụng cho cả tuning và training cuối; cấu hình trong configs/tuning.json.

In [2]:
from notebook_workflow import run_experiments, selected_params
SCENARIOS = None  # hoặc ['federated'], ['centralized'], ['local_unsw','local_bot','local_cic']

In [3]:
display(selected_params(C,'dnn'))
results_dnn = run_experiments('dnn', CONFIG, scenarios=SCENARIOS)
display(results_dnn)

{'study_identity': 'a918907e0ec7b70ed015ce689de6904b02ed6f517bb383caba216fd40749af66',
 'model': 'dnn',
 'trial': 9,
 'params': {'architecture': '16-8-4',
  'dropout': 0.4,
  'batch_size': 4096,
  'client_learning_rate': 0.002,
  'server_learning_rate': 0.01},
 'rank': [0.7695237209251039, 0.8481094127111827, 0.7709171313391866],
 'completed_trials': 10,
 'required_trials': 10,
 'ready_for_final': True,
 'test_used_for_selection': False,
 'objective': 'mean of 12 three-client comparison F1 values; Local/Centralized at minimum val_loss epoch, FL at final round'}

2026-10-24 08:45:25.346170: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2026-10-24 08:45:25.346237: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2026-10-24 08:45:25.346265: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2026-10-24 08:45:27.516413: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2026-10-24 08:45:27.516469: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2026-10-24 08:45:27.516486: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
{
  "python": "3.10.12 (main, Aug 31 2026, 10:18:17) [GCC 11.4.0]",
  "tensorflow": "2.14.1",
  "tff": "0.87.0",
  "gpu": "NVIDIA GeForce GTX 1660 SUPER",
  "tff_worker_sha256": "abefbf6842678c47a33857b8f177b771110656198c670d02b9c04ef11da8af2a",
  "tensorflow_gpu_probe": "passed",
  "tff_cuda_only_probe": "passed"
}
dnn/local_unsw/test: epoch 1/45, loss=0.703384, val_loss=0.610668, wait=0/5
dnn/local_unsw/test: epoch 2/45, loss=0.598881, val_loss=0.505389, wait=0/5
dnn/local_unsw/test: epoch 3/45, loss=0.478966, val_loss=0.293715, wait=0/5
dnn/local_unsw/test: epoch 4/45, loss=0.330421, val_loss=0.150480, wait=0/5
dnn/local_unsw/test: epoch 5/45, loss=0.223014, val_loss=0.099748, wait=0/5
dnn/local_unsw/test: epoch 6/45, loss=0.167406, val_loss=0.085133, wait=0/5
dnn/local_unsw/test: epoch 7/45, loss=0.143960, val_loss=0.079341, wait=0/5
dnn/local_unsw/test: epoch 8/45, loss=0.128988, val_loss=0.073466, wait=0/5
dnn/local_unsw/test: epoch 9/45, loss=0.120238, val_loss=0.066467, wait=0/5
dnn/local_unsw/test: epoch 10/45, loss=0.113263, val_loss=0.060534, wait=0/5
dnn/local_unsw/test: epoch 11/45, loss=0.107968, val_loss=0.055009, wait=0/5
dnn/local_unsw/test: epoch 12/45, loss=0.103191, val_loss=0.049352, wait=0/5
dnn/local_unsw/test: epoch 13/45, loss=0.099682, val_loss=0.044626, wait=0/5
dnn/local_unsw/test: epoch 14/45, loss=0.097487, val_loss=0.039505, wait=0/5
dnn/local_unsw/test: epoch 15/45, loss=0.094311, val_loss=0.037574, wait=0/5
dnn/local_unsw/test: epoch 16/45, loss=0.093096, val_loss=0.035444, wait=0/5
dnn/local_unsw/test: epoch 17/45, loss=0.091263, val_loss=0.033100, wait=0/5
dnn/local_unsw/test: epoch 18/45, loss=0.086839, val_loss=0.031744, wait=0/5
dnn/local_unsw/test: epoch 19/45, loss=0.081832, val_loss=0.030883, wait=0/5
dnn/local_unsw/test: epoch 20/45, loss=0.076244, val_loss=0.029362, wait=0/5
dnn/local_unsw/test: epoch 21/45, loss=0.073566, val_loss=0.029314, wait=0/5
dnn/local_unsw/test: epoch 22/45, loss=0.071146, val_loss=0.028134, wait=0/5
dnn/local_unsw/test: epoch 23/45, loss=0.068152, val_loss=0.027982, wait=0/5
dnn/local_unsw/test: epoch 24/45, loss=0.067618, val_loss=0.028198, wait=1/5
dnn/local_unsw/test: epoch 25/45, loss=0.067743, val_loss=0.026287, wait=0/5
dnn/local_unsw/test: epoch 26/45, loss=0.064976, val_loss=0.026175, wait=0/5
dnn/local_unsw/test: epoch 27/45, loss=0.063710, val_loss=0.026183, wait=1/5
dnn/local_unsw/test: epoch 28/45, loss=0.057838, val_loss=0.026838, wait=2/5
dnn/local_unsw/test: epoch 29/45, loss=0.053857, val_loss=0.026239, wait=3/5
dnn/local_unsw/test: epoch 30/45, loss=0.051968, val_loss=0.026226, wait=4/5
dnn/local_unsw/test: epoch 31/45, loss=0.050222, val_loss=0.025708, wait=0/5
dnn/local_unsw/test: epoch 32/45, loss=0.051006, val_loss=0.024678, wait=0/5
dnn/local_unsw/test: epoch 33/45, loss=0.049669, val_loss=0.024528, wait=0/5
dnn/local_unsw/test: epoch 34/45, loss=0.048971, val_loss=0.024434, wait=0/5
dnn/local_unsw/test: epoch 35/45, loss=0.047250, val_loss=0.023818, wait=0/5
dnn/local_unsw/test: epoch 36/45, loss=0.048476, val_loss=0.024575, wait=1/5
dnn/local_unsw/test: epoch 37/45, loss=0.046734, val_loss=0.023814, wait=0/5
dnn/local_unsw/test: epoch 38/45, loss=0.047239, val_loss=0.023491, wait=0/5
dnn/local_unsw/test: epoch 39/45, loss=0.047015, val_loss=0.023638, wait=1/5
dnn/local_unsw/test: epoch 40/45, loss=0.045243, val_loss=0.024002, wait=2/5
dnn/local_unsw/test: epoch 41/45, loss=0.045374, val_loss=0.023786, wait=3/5
dnn/local_unsw/test: epoch 42/45, loss=0.045387, val_loss=0.023015, wait=0/5
dnn/local_unsw/test: epoch 43/45, loss=0.045266, val_loss=0.022964, wait=0/5
dnn/local_unsw/test: epoch 44/45, loss=0.045515, val_loss=0.022795, wait=0/5
dnn/local_unsw/test: epoch 45/45, loss=0.044414, val_loss=0.022133, wait=0/5
RESTORE dnn/local_unsw: epoch 45 with minimum val_loss; no refit.
dnn/local_bot/test: epoch 1/45, loss=0.614448, val_loss=0.536798, wait=0/5
dnn/local_bot/test: epoch 2/45, loss=0.473668, val_loss=0.372543, wait=0/5
dnn/local_bot/test: epoch 3/45, loss=0.307964, val_loss=0.193134, wait=0/5
dnn/local_bot/test: epoch 4/45, loss=0.196936, val_loss=0.139324, wait=0/5
dnn/local_bot/test: epoch 5/45, loss=0.149767, val_loss=0.124871, wait=0/5
dnn/local_bot/test: epoch 6/45, loss=0.131401, val_loss=0.153077, wait=1/5
dnn/local_bot/test: epoch 7/45, loss=0.119861, val_loss=0.172240, wait=2/5
dnn/local_bot/test: epoch 8/45, loss=0.112728, val_loss=0.197695, wait=3/5
dnn/local_bot/test: epoch 9/45, loss=0.108556, val_loss=0.214979, wait=4/5
dnn/local_bot/test: epoch 10/45, loss=0.102746, val_loss=0.243614, wait=5/5
EARLY STOP dnn/local_bot: 5 epochs without val_loss improvement; no refit.
RESTORE dnn/local_bot: epoch 5 with minimum val_loss; no refit.
dnn/local_cic/test: epoch 1/45, loss=0.428998, val_loss=0.147961, wait=0/5
dnn/local_cic/test: epoch 2/45, loss=0.208562, val_loss=0.123674, wait=0/5
dnn/local_cic/test: epoch 3/45, loss=0.176079, val_loss=0.127740, wait=1/5
dnn/local_cic/test: epoch 4/45, loss=0.162478, val_loss=0.132226, wait=2/5
dnn/local_cic/test: epoch 5/45, loss=0.153135, val_loss=0.134176, wait=3/5
dnn/local_cic/test: epoch 6/45, loss=0.140969, val_loss=0.130881, wait=4/5
dnn/local_cic/test: epoch 7/45, loss=0.131009, val_loss=0.141703, wait=5/5
EARLY STOP dnn/local_cic: 5 epochs without val_loss improvement; no refit.
RESTORE dnn/local_cic: epoch 2 with minimum val_loss; no refit.
dnn/centralized/test: epoch 1/45, loss=0.401893, val_loss=0.170325, wait=0/5
dnn/centralized/test: epoch 2/45, loss=0.213586, val_loss=0.141239, wait=0/5
dnn/centralized/test: epoch 3/45, loss=0.176615, val_loss=0.132594, wait=0/5
dnn/centralized/test: epoch 4/45, loss=0.157564, val_loss=0.128560, wait=0/5
dnn/centralized/test: epoch 5/45, loss=0.147161, val_loss=0.128363, wait=0/5
dnn/centralized/test: epoch 6/45, loss=0.140903, val_loss=0.123382, wait=0/5
dnn/centralized/test: epoch 7/45, loss=0.136129, val_loss=0.120835, wait=0/5
dnn/centralized/test: epoch 8/45, loss=0.133134, val_loss=0.120176, wait=0/5
dnn/centralized/test: epoch 9/45, loss=0.131183, val_loss=0.119925, wait=0/5
dnn/centralized/test: epoch 10/45, loss=0.129279, val_loss=0.120049, wait=1/5
dnn/centralized/test: epoch 11/45, loss=0.128706, val_loss=0.120341, wait=2/5
dnn/centralized/test: epoch 12/45, loss=0.127062, val_loss=0.120516, wait=3/5
dnn/centralized/test: epoch 13/45, loss=0.126331, val_loss=0.119460, wait=0/5
dnn/centralized/test: epoch 14/45, loss=0.125842, val_loss=0.121425, wait=1/5
dnn/centralized/test: epoch 15/45, loss=0.124654, val_loss=0.120033, wait=2/5
dnn/centralized/test: epoch 16/45, loss=0.124307, val_loss=0.121166, wait=3/5
dnn/centralized/test: epoch 17/45, loss=0.124210, val_loss=0.121884, wait=4/5
dnn/centralized/test: epoch 18/45, loss=0.122850, val_loss=0.121643, wait=5/5
EARLY STOP dnn/centralized: 5 epochs without val_loss improvement; no refit.
RESTORE dnn/centralized: epoch 13 with minimum val_loss; no refit.
dnn/federated/test: round 1/15 | test reserved for final round
dnn/federated/test: round 2/15 | test reserved for final round
dnn/federated/test: round 3/15 | test reserved for final round
dnn/federated/test: round 4/15 | test reserved for final round
dnn/federated/test: round 5/15 | test reserved for final round
dnn/federated/test: round 6/15 | test reserved for final round
dnn/federated/test: round 7/15 | test reserved for final round
dnn/federated/test: round 8/15 | test reserved for final round
dnn/federated/test: round 9/15 | test reserved for final round
dnn/federated/test: round 10/15 | test reserved for final round
dnn/federated/test: round 11/15 | test reserved for final round
dnn/federated/test: round 12/15 | test reserved for final round
dnn/federated/test: round 13/15 | test reserved for final round
dnn/federated/test: round 14/15 | test reserved for final round
dnn/federated/test: round 15/15 | test reserved for final round

,model,scenario,source,test_dataset,samples,accuracy,precision,recall,f1,far,auc,tn,fp,fn,tp
0,dnn,centralized,all_clients,unsw,57032,0.991741,0.989869,0.993653,0.991757,0.010170,0.995116,28226,290,181,28335
1,dnn,centralized,all_clients,bot,81023,0.965553,0.997914,0.933055,0.964396,0.001950,0.994791,40433,79,2712,37799
2,dnn,centralized,all_clients,cic,300000,0.976873,0.997213,0.956420,0.976390,0.002673,0.985847,149599,401,6537,143463
3,dnn,federated,all_clients,unsw,57032,0.842299,0.925427,0.744600,0.825223,0.060001,0.906755,26805,1711,7283,21233
4,dnn,federated,all_clients,bot,81023,0.954605,0.978289,0.929846,0.953452,0.020636,0.979922,39676,836,2842,37669
5,dnn,federated,all_clients,cic,300000,0.900773,0.892392,0.911453,0.901822,0.109907,0.943370,133514,16486,13282,136718
6,dnn,local,bot,unsw,57032,0.844035,0.865096,0.815191,0.839403,0.127122,0.891705,24891,3625,5270,23246
7,dnn,local,bot,bot,81023,0.968996,0.995359,0.942386,0.968149,0.004394,0.996686,40334,178,2334,38177
8,dnn,local,bot,cic,300000,0.726177,0.726205,0.726113,0.726159,0.273760,0.656884,108936,41064,41083,108917
9,dnn,local,cic,unsw,57032,0.476890,0.471373,0.380523,0.421104,0.426743,0.445846,16347,12169,17665,10851
10,dnn,local,cic,bot,81023,0.378929,0.363241,0.321592,0.341150,0.563734,0.399319,17674,22838,27483,13028
11,dnn,local,cic,cic,300000,0.971853,0.986955,0.956347,0.971410,0.012640,0.981765,148104,1896,6548,143452
12,dnn,local,unsw,unsw,57032,0.996283,0.993170,0.999439,0.996294,0.006873,0.998339,28320,196,16,28500
13,dnn,local,unsw,bot,81023,0.754921,0.690247,0.924885,0.790523,0.415038,0.826377,23698,16814,3043,37468
14,dnn,local,unsw,cic,300000,0.617213,0.573190,0.917960,0.705718,0.683533,0.544399,47470,102530,12306,137694

In [4]:
display(selected_params(C,'lstm'))
results_lstm = run_experiments('lstm', CONFIG, scenarios=SCENARIOS)
display(results_lstm)

{'study_identity': 'a918907e0ec7b70ed015ce689de6904b02ed6f517bb383caba216fd40749af66',
 'model': 'lstm',
 'trial': 7,
 'params': {'architecture': '16-8-4',
  'dropout': 0.3,
  'batch_size': 1024,
  'client_learning_rate': 0.001,
  'server_learning_rate': 0.075},
 'rank': [0.7585189050395194, 0.7279253409906676, 0.7606622087878455],
 'completed_trials': 10,
 'required_trials': 10,
 'ready_for_final': True,
 'test_used_for_selection': False,
 'objective': 'mean of 12 three-client comparison F1 values; Local/Centralized at minimum val_loss epoch, FL at final round'}

2026-10-24 08:51:37.215724: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2026-10-24 08:51:37.215775: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2026-10-24 08:51:37.215809: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2026-10-24 08:51:39.292775: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2026-10-24 08:51:39.292844: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2026-10-24 08:51:39.292861: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
{
  "python": "3.10.12 (main, Aug 31 2026, 10:18:17) [GCC 11.4.0]",
  "tensorflow": "2.14.1",
  "tff": "0.87.0",
  "gpu": "NVIDIA GeForce GTX 1660 SUPER",
  "tff_worker_sha256": "abefbf6842678c47a33857b8f177b771110656198c670d02b9c04ef11da8af2a",
  "tensorflow_gpu_probe": "passed",
  "tff_cuda_only_probe": "passed"
}
lstm/local_unsw/test: epoch 1/45, loss=0.651385, val_loss=0.540286, wait=0/5
lstm/local_unsw/test: epoch 2/45, loss=0.406199, val_loss=0.251443, wait=0/5
lstm/local_unsw/test: epoch 3/45, loss=0.210869, val_loss=0.147154, wait=0/5
lstm/local_unsw/test: epoch 4/45, loss=0.138377, val_loss=0.105445, wait=0/5
lstm/local_unsw/test: epoch 5/45, loss=0.103033, val_loss=0.084033, wait=0/5
lstm/local_unsw/test: epoch 6/45, loss=0.083201, val_loss=0.072290, wait=0/5
lstm/local_unsw/test: epoch 7/45, loss=0.069591, val_loss=0.063407, wait=0/5
lstm/local_unsw/test: epoch 8/45, loss=0.060366, val_loss=0.056915, wait=0/5
lstm/local_unsw/test: epoch 9/45, loss=0.053618, val_loss=0.051789, wait=0/5
lstm/local_unsw/test: epoch 10/45, loss=0.048876, val_loss=0.047978, wait=0/5
lstm/local_unsw/test: epoch 11/45, loss=0.045057, val_loss=0.044758, wait=0/5
lstm/local_unsw/test: epoch 12/45, loss=0.041865, val_loss=0.038171, wait=0/5
lstm/local_unsw/test: epoch 13/45, loss=0.039495, val_loss=0.037009, wait=0/5
lstm/local_unsw/test: epoch 14/45, loss=0.037361, val_loss=0.035967, wait=0/5
lstm/local_unsw/test: epoch 15/45, loss=0.036049, val_loss=0.034991, wait=0/5
lstm/local_unsw/test: epoch 16/45, loss=0.034841, val_loss=0.034198, wait=0/5
lstm/local_unsw/test: epoch 17/45, loss=0.033720, val_loss=0.033564, wait=0/5
lstm/local_unsw/test: epoch 18/45, loss=0.032862, val_loss=0.032268, wait=0/5
lstm/local_unsw/test: epoch 19/45, loss=0.031857, val_loss=0.032689, wait=1/5
lstm/local_unsw/test: epoch 20/45, loss=0.031268, val_loss=0.031904, wait=0/5
lstm/local_unsw/test: epoch 21/45, loss=0.030585, val_loss=0.030972, wait=0/5
lstm/local_unsw/test: epoch 22/45, loss=0.029990, val_loss=0.029356, wait=0/5
lstm/local_unsw/test: epoch 23/45, loss=0.029512, val_loss=0.030499, wait=1/5
lstm/local_unsw/test: epoch 24/45, loss=0.029258, val_loss=0.030089, wait=2/5
lstm/local_unsw/test: epoch 25/45, loss=0.028025, val_loss=0.026435, wait=0/5
lstm/local_unsw/test: epoch 26/45, loss=0.025986, val_loss=0.024029, wait=0/5
lstm/local_unsw/test: epoch 27/45, loss=0.025680, val_loss=0.023441, wait=0/5
lstm/local_unsw/test: epoch 28/45, loss=0.025133, val_loss=0.023764, wait=1/5
lstm/local_unsw/test: epoch 29/45, loss=0.024758, val_loss=0.022741, wait=0/5
lstm/local_unsw/test: epoch 30/45, loss=0.024467, val_loss=0.022835, wait=1/5
lstm/local_unsw/test: epoch 31/45, loss=0.024490, val_loss=0.022380, wait=0/5
lstm/local_unsw/test: epoch 32/45, loss=0.024055, val_loss=0.023206, wait=1/5
lstm/local_unsw/test: epoch 33/45, loss=0.023609, val_loss=0.022673, wait=2/5
lstm/local_unsw/test: epoch 34/45, loss=0.023569, val_loss=0.021874, wait=0/5
lstm/local_unsw/test: epoch 35/45, loss=0.023521, val_loss=0.022572, wait=1/5
lstm/local_unsw/test: epoch 36/45, loss=0.023636, val_loss=0.022198, wait=2/5
lstm/local_unsw/test: epoch 37/45, loss=0.023308, val_loss=0.022519, wait=3/5
lstm/local_unsw/test: epoch 38/45, loss=0.023246, val_loss=0.023271, wait=4/5
lstm/local_unsw/test: epoch 39/45, loss=0.023020, val_loss=0.022899, wait=5/5
EARLY STOP lstm/local_unsw: 5 epochs without val_loss improvement; no refit.
RESTORE lstm/local_unsw: epoch 34 with minimum val_loss; no refit.
lstm/local_bot/test: epoch 1/45, loss=0.592442, val_loss=0.427652, wait=0/5
lstm/local_bot/test: epoch 2/45, loss=0.299500, val_loss=0.256825, wait=0/5
lstm/local_bot/test: epoch 3/45, loss=0.187664, val_loss=0.196397, wait=0/5
lstm/local_bot/test: epoch 4/45, loss=0.146757, val_loss=0.174360, wait=0/5
lstm/local_bot/test: epoch 5/45, loss=0.112016, val_loss=0.166993, wait=0/5
lstm/local_bot/test: epoch 6/45, loss=0.069393, val_loss=0.169026, wait=1/5
lstm/local_bot/test: epoch 7/45, loss=0.049786, val_loss=0.172310, wait=2/5
lstm/local_bot/test: epoch 8/45, loss=0.039050, val_loss=0.176853, wait=3/5
lstm/local_bot/test: epoch 9/45, loss=0.032760, val_loss=0.180706, wait=4/5
lstm/local_bot/test: epoch 10/45, loss=0.027964, val_loss=0.184057, wait=5/5
EARLY STOP lstm/local_bot: 5 epochs without val_loss improvement; no refit.
RESTORE lstm/local_bot: epoch 5 with minimum val_loss; no refit.
lstm/local_cic/test: epoch 1/45, loss=0.336788, val_loss=0.121477, wait=0/5
lstm/local_cic/test: epoch 2/45, loss=0.116769, val_loss=0.098511, wait=0/5
lstm/local_cic/test: epoch 3/45, loss=0.102169, val_loss=0.093291, wait=0/5
lstm/local_cic/test: epoch 4/45, loss=0.097775, val_loss=0.091579, wait=0/5
lstm/local_cic/test: epoch 5/45, loss=0.095515, val_loss=0.090742, wait=0/5
lstm/local_cic/test: epoch 6/45, loss=0.093890, val_loss=0.088888, wait=0/5
lstm/local_cic/test: epoch 7/45, loss=0.092085, val_loss=0.086528, wait=0/5
lstm/local_cic/test: epoch 8/45, loss=0.090782, val_loss=0.085650, wait=0/5
lstm/local_cic/test: epoch 9/45, loss=0.089783, val_loss=0.085054, wait=0/5
lstm/local_cic/test: epoch 10/45, loss=0.088862, val_loss=0.084537, wait=0/5
lstm/local_cic/test: epoch 11/45, loss=0.087940, val_loss=0.084269, wait=0/5
lstm/local_cic/test: epoch 12/45, loss=0.087889, val_loss=0.083986, wait=0/5
lstm/local_cic/test: epoch 13/45, loss=0.087000, val_loss=0.083723, wait=0/5
lstm/local_cic/test: epoch 14/45, loss=0.086965, val_loss=0.083571, wait=0/5
lstm/local_cic/test: epoch 15/45, loss=0.086614, val_loss=0.083421, wait=0/5
lstm/local_cic/test: epoch 16/45, loss=0.086278, val_loss=0.083104, wait=0/5
lstm/local_cic/test: epoch 17/45, loss=0.086125, val_loss=0.082831, wait=0/5
lstm/local_cic/test: epoch 18/45, loss=0.085780, val_loss=0.082489, wait=0/5
lstm/local_cic/test: epoch 19/45, loss=0.085604, val_loss=0.082464, wait=0/5
lstm/local_cic/test: epoch 20/45, loss=0.085275, val_loss=0.082177, wait=0/5
lstm/local_cic/test: epoch 21/45, loss=0.084902, val_loss=0.082055, wait=0/5
lstm/local_cic/test: epoch 22/45, loss=0.084715, val_loss=0.081953, wait=0/5
lstm/local_cic/test: epoch 23/45, loss=0.084278, val_loss=0.081484, wait=0/5
lstm/local_cic/test: epoch 24/45, loss=0.084125, val_loss=0.081432, wait=0/5
lstm/local_cic/test: epoch 25/45, loss=0.084117, val_loss=0.081326, wait=0/5
lstm/local_cic/test: epoch 26/45, loss=0.083679, val_loss=0.080965, wait=0/5
lstm/local_cic/test: epoch 27/45, loss=0.083426, val_loss=0.081165, wait=1/5
lstm/local_cic/test: epoch 28/45, loss=0.083356, val_loss=0.081099, wait=2/5
lstm/local_cic/test: epoch 29/45, loss=0.083213, val_loss=0.080592, wait=0/5
lstm/local_cic/test: epoch 30/45, loss=0.082728, val_loss=0.080529, wait=0/5
lstm/local_cic/test: epoch 31/45, loss=0.082523, val_loss=0.080227, wait=0/5
lstm/local_cic/test: epoch 32/45, loss=0.082453, val_loss=0.079890, wait=0/5
lstm/local_cic/test: epoch 33/45, loss=0.082305, val_loss=0.080147, wait=1/5
lstm/local_cic/test: epoch 34/45, loss=0.082040, val_loss=0.079822, wait=0/5
lstm/local_cic/test: epoch 35/45, loss=0.081873, val_loss=0.079698, wait=0/5
lstm/local_cic/test: epoch 36/45, loss=0.081635, val_loss=0.079751, wait=1/5
lstm/local_cic/test: epoch 37/45, loss=0.081468, val_loss=0.079671, wait=0/5
lstm/local_cic/test: epoch 38/45, loss=0.081217, val_loss=0.079703, wait=1/5
lstm/local_cic/test: epoch 39/45, loss=0.081084, val_loss=0.079682, wait=2/5
lstm/local_cic/test: epoch 40/45, loss=0.081166, val_loss=0.079506, wait=0/5
lstm/local_cic/test: epoch 41/45, loss=0.080822, val_loss=0.079691, wait=1/5
lstm/local_cic/test: epoch 42/45, loss=0.080750, val_loss=0.079561, wait=2/5
lstm/local_cic/test: epoch 43/45, loss=0.080515, val_loss=0.079458, wait=0/5
lstm/local_cic/test: epoch 44/45, loss=0.080600, val_loss=0.079418, wait=0/5
lstm/local_cic/test: epoch 45/45, loss=0.080494, val_loss=0.079225, wait=0/5
RESTORE lstm/local_cic: epoch 45 with minimum val_loss; no refit.
lstm/centralized/test: epoch 1/45, loss=0.290473, val_loss=0.153492, wait=0/5
lstm/centralized/test: epoch 2/45, loss=0.129746, val_loss=0.137970, wait=0/5
lstm/centralized/test: epoch 3/45, loss=0.118122, val_loss=0.135140, wait=0/5
lstm/centralized/test: epoch 4/45, loss=0.113996, val_loss=0.132321, wait=0/5
lstm/centralized/test: epoch 5/45, loss=0.111424, val_loss=0.130819, wait=0/5
lstm/centralized/test: epoch 6/45, loss=0.108592, val_loss=0.125491, wait=0/5
lstm/centralized/test: epoch 7/45, loss=0.099990, val_loss=0.111672, wait=0/5
lstm/centralized/test: epoch 8/45, loss=0.092532, val_loss=0.102269, wait=0/5
lstm/centralized/test: epoch 9/45, loss=0.087309, val_loss=0.098250, wait=0/5
lstm/centralized/test: epoch 10/45, loss=0.083014, val_loss=0.097955, wait=0/5
lstm/centralized/test: epoch 11/45, loss=0.080308, val_loss=0.098488, wait=1/5
lstm/centralized/test: epoch 12/45, loss=0.078664, val_loss=0.097134, wait=0/5
lstm/centralized/test: epoch 13/45, loss=0.076998, val_loss=0.097935, wait=1/5
lstm/centralized/test: epoch 14/45, loss=0.075371, val_loss=0.098886, wait=2/5
lstm/centralized/test: epoch 15/45, loss=0.074050, val_loss=0.099644, wait=3/5
lstm/centralized/test: epoch 16/45, loss=0.072928, val_loss=0.099533, wait=4/5
lstm/centralized/test: epoch 17/45, loss=0.072088, val_loss=0.100629, wait=5/5
EARLY STOP lstm/centralized: 5 epochs without val_loss improvement; no refit.
RESTORE lstm/centralized: epoch 12 with minimum val_loss; no refit.
lstm/federated/test: round 1/15 | test reserved for final round
lstm/federated/test: round 2/15 | test reserved for final round
lstm/federated/test: round 3/15 | test reserved for final round
lstm/federated/test: round 4/15 | test reserved for final round
lstm/federated/test: round 5/15 | test reserved for final round
lstm/federated/test: round 6/15 | test reserved for final round
lstm/federated/test: round 7/15 | test reserved for final round
lstm/federated/test: round 8/15 | test reserved for final round
lstm/federated/test: round 9/15 | test reserved for final round
lstm/federated/test: round 10/15 | test reserved for final round
lstm/federated/test: round 11/15 | test reserved for final round
lstm/federated/test: round 12/15 | test reserved for final round
lstm/federated/test: round 13/15 | test reserved for final round
lstm/federated/test: round 14/15 | test reserved for final round
lstm/federated/test: round 15/15 | test reserved for final round

,model,scenario,source,test_dataset,samples,accuracy,precision,recall,f1,far,auc,tn,fp,fn,tp
0,dnn,centralized,all_clients,unsw,57032,0.991741,0.989869,0.993653,0.991757,0.010170,0.995116,28226,290,181,28335
1,dnn,centralized,all_clients,bot,81023,0.965553,0.997914,0.933055,0.964396,0.001950,0.994791,40433,79,2712,37799
2,dnn,centralized,all_clients,cic,300000,0.976873,0.997213,0.956420,0.976390,0.002673,0.985847,149599,401,6537,143463
3,dnn,federated,all_clients,unsw,57032,0.842299,0.925427,0.744600,0.825223,0.060001,0.906755,26805,1711,7283,21233
4,dnn,federated,all_clients,bot,81023,0.954605,0.978289,0.929846,0.953452,0.020636,0.979922,39676,836,2842,37669
5,dnn,federated,all_clients,cic,300000,0.900773,0.892392,0.911453,0.901822,0.109907,0.943370,133514,16486,13282,136718
6,dnn,local,bot,unsw,57032,0.844035,0.865096,0.815191,0.839403,0.127122,0.891705,24891,3625,5270,23246
7,dnn,local,bot,bot,81023,0.968996,0.995359,0.942386,0.968149,0.004394,0.996686,40334,178,2334,38177
8,dnn,local,bot,cic,300000,0.726177,0.726205,0.726113,0.726159,0.273760,0.656884,108936,41064,41083,108917
9,dnn,local,cic,unsw,57032,0.476890,0.471373,0.380523,0.421104,0.426743,0.445846,16347,12169,17665,10851
10,dnn,local,cic,bot,81023,0.378929,0.363241,0.321592,0.341150,0.563734,0.399319,17674,22838,27483,13028
11,dnn,local,cic,cic,300000,0.971853,0.986955,0.956347,0.971410,0.012640,0.981765,148104,1896,6548,143452
12,dnn,local,unsw,unsw,57032,0.996283,0.993170,0.999439,0.996294,0.006873,0.998339,28320,196,16,28500
13,dnn,local,unsw,bot,81023,0.754921,0.690247,0.924885,0.790523,0.415038,0.826377,23698,16814,3043,37468
14,dnn,local,unsw,cic,300000,0.617213,0.573190,0.917960,0.705718,0.683533,0.544399,47470,102530,12306,137694
15,lstm,centralized,all_clients,unsw,57032,0.996879,0.994762,0.999018,0.996886,0.005260,0.998623,28366,150,28,28488
16,lstm,centralized,all_clients,bot,81023,0.993533,0.999550,0.987510,0.993493,0.000444,0.997376,40494,18,506,40005
17,lstm,centralized,all_clients,cic,300000,0.978300,0.998957,0.957600,0.977841,0.001000,0.986000,149850,150,6360,143640
18,lstm,federated,all_clients,unsw,57032,0.818523,0.960552,0.664329,0.785439,0.027283,0.962163,27738,778,9572,18944
19,lstm,federated,all_clients,bot,81023,0.955605,0.958513,0.952433,0.955463,0.041222,0.991393,38842,1670,1927,38584
20,lstm,federated,all_clients,cic,300000,0.924247,0.951480,0.894087,0.921891,0.045593,0.952348,143161,6839,15887,134113
21,lstm,local,bot,unsw,57032,0.786436,0.786939,0.785559,0.786248,0.212688,0.863079,22451,6065,6115,22401
22,lstm,local,bot,bot,81023,0.975254,0.997854,0.952556,0.974679,0.002049,0.994733,40429,83,1922,38589
23,lstm,local,bot,cic,300000,0.658193,0.646109,0.699547,0.671767,0.383160,0.743613,92526,57474,45068,104932
24,lstm,local,cic,unsw,57032,0.437404,0.384928,0.209391,0.271236,0.334584,0.267473,18975,9541,22545,5971
25,lstm,local,cic,bot,81023,0.351147,0.253344,0.152897,0.190702,0.450607,0.210427,22257,18255,34317,6194
26,lstm,local,cic,cic,300000,0.979777,0.999479,0.960053,0.979370,0.000500,0.988928,149925,75,5992,144008
27,lstm,local,unsw,unsw,57032,0.996563,0.993277,0.999895,0.996575,0.006768,0.996300,28323,193,3,28513
28,lstm,local,unsw,bot,81023,0.866680,0.824256,0.932093,0.874864,0.198731,0.885996,32461,8051,2751,37760
29,lstm,local,unsw,cic,300000,0.676513,0.613943,0.951080,0.746199,0.598053,0.674283,60292,89708,7338,142662

In [5]:
display(selected_params(C,'cnn'))
results_cnn = run_experiments('cnn', CONFIG, scenarios=SCENARIOS)
display(results_cnn)

{'study_identity': 'a918907e0ec7b70ed015ce689de6904b02ed6f517bb383caba216fd40749af66',
 'model': 'cnn',
 'trial': 10,
 'params': {'architecture': '4-8-4',
  'dropout': 0.1,
  'batch_size': 1024,
  'client_learning_rate': 0.0003,
  'server_learning_rate': 0.01,
  'kernel_size': 3},
 'rank': [0.8224010022235628, 0.8744021427204898, 0.8444676932676125],
 'completed_trials': 10,
 'required_trials': 10,
 'ready_for_final': True,
 'test_used_for_selection': False,
 'objective': 'mean of 12 three-client comparison F1 values; Local/Centralized at minimum val_loss epoch, FL at final round'}

2026-10-24 09:09:39.403703: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2026-10-24 09:09:39.403752: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2026-10-24 09:09:39.403771: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2026-10-24 09:09:41.566814: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2026-10-24 09:09:41.566871: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2026-10-24 09:09:41.566887: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
{
  "python": "3.10.12 (main, Aug 31 2026, 10:18:17) [GCC 11.4.0]",
  "tensorflow": "2.14.1",
  "tff": "0.87.0",
  "gpu": "NVIDIA GeForce GTX 1660 SUPER",
  "tff_worker_sha256": "abefbf6842678c47a33857b8f177b771110656198c670d02b9c04ef11da8af2a",
  "tensorflow_gpu_probe": "passed",
  "tff_cuda_only_probe": "passed"
}
cnn/local_unsw/test: epoch 1/45, loss=0.603136, val_loss=0.480148, wait=0/5
cnn/local_unsw/test: epoch 2/45, loss=0.404953, val_loss=0.280941, wait=0/5
cnn/local_unsw/test: epoch 3/45, loss=0.272768, val_loss=0.171182, wait=0/5
cnn/local_unsw/test: epoch 4/45, loss=0.193208, val_loss=0.127177, wait=0/5
cnn/local_unsw/test: epoch 5/45, loss=0.149976, val_loss=0.109803, wait=0/5
cnn/local_unsw/test: epoch 6/45, loss=0.127582, val_loss=0.099326, wait=0/5
cnn/local_unsw/test: epoch 7/45, loss=0.115034, val_loss=0.091553, wait=0/5
cnn/local_unsw/test: epoch 8/45, loss=0.106534, val_loss=0.085922, wait=0/5
cnn/local_unsw/test: epoch 9/45, loss=0.099671, val_loss=0.082145, wait=0/5
cnn/local_unsw/test: epoch 10/45, loss=0.094349, val_loss=0.078508, wait=0/5
cnn/local_unsw/test: epoch 11/45, loss=0.091016, val_loss=0.076185, wait=0/5
cnn/local_unsw/test: epoch 12/45, loss=0.088747, val_loss=0.070849, wait=0/5
cnn/local_unsw/test: epoch 13/45, loss=0.085375, val_loss=0.067382, wait=0/5
cnn/local_unsw/test: epoch 14/45, loss=0.083480, val_loss=0.062720, wait=0/5
cnn/local_unsw/test: epoch 15/45, loss=0.081272, val_loss=0.056619, wait=0/5
cnn/local_unsw/test: epoch 16/45, loss=0.078637, val_loss=0.049900, wait=0/5
cnn/local_unsw/test: epoch 17/45, loss=0.077314, val_loss=0.045794, wait=0/5
cnn/local_unsw/test: epoch 18/45, loss=0.075180, val_loss=0.043283, wait=0/5
cnn/local_unsw/test: epoch 19/45, loss=0.073362, val_loss=0.039641, wait=0/5
cnn/local_unsw/test: epoch 20/45, loss=0.071214, val_loss=0.037640, wait=0/5
cnn/local_unsw/test: epoch 21/45, loss=0.071005, val_loss=0.035644, wait=0/5
cnn/local_unsw/test: epoch 22/45, loss=0.070123, val_loss=0.035019, wait=0/5
cnn/local_unsw/test: epoch 23/45, loss=0.068019, val_loss=0.032738, wait=0/5
cnn/local_unsw/test: epoch 24/45, loss=0.067699, val_loss=0.031747, wait=0/5
cnn/local_unsw/test: epoch 25/45, loss=0.065148, val_loss=0.031105, wait=0/5
cnn/local_unsw/test: epoch 26/45, loss=0.065489, val_loss=0.030109, wait=0/5
cnn/local_unsw/test: epoch 27/45, loss=0.063875, val_loss=0.028519, wait=0/5
cnn/local_unsw/test: epoch 28/45, loss=0.063306, val_loss=0.028687, wait=1/5
cnn/local_unsw/test: epoch 29/45, loss=0.062477, val_loss=0.027736, wait=0/5
cnn/local_unsw/test: epoch 30/45, loss=0.061516, val_loss=0.027425, wait=0/5
cnn/local_unsw/test: epoch 31/45, loss=0.061422, val_loss=0.026861, wait=0/5
cnn/local_unsw/test: epoch 32/45, loss=0.060256, val_loss=0.025992, wait=0/5
cnn/local_unsw/test: epoch 33/45, loss=0.059175, val_loss=0.025891, wait=0/5
cnn/local_unsw/test: epoch 34/45, loss=0.058736, val_loss=0.025368, wait=0/5
cnn/local_unsw/test: epoch 35/45, loss=0.058410, val_loss=0.025526, wait=1/5
cnn/local_unsw/test: epoch 36/45, loss=0.059192, val_loss=0.024837, wait=0/5
cnn/local_unsw/test: epoch 37/45, loss=0.058079, val_loss=0.025265, wait=1/5
cnn/local_unsw/test: epoch 38/45, loss=0.058361, val_loss=0.023885, wait=0/5
cnn/local_unsw/test: epoch 39/45, loss=0.056372, val_loss=0.024084, wait=1/5
cnn/local_unsw/test: epoch 40/45, loss=0.056500, val_loss=0.023949, wait=2/5
cnn/local_unsw/test: epoch 41/45, loss=0.055473, val_loss=0.023973, wait=3/5
cnn/local_unsw/test: epoch 42/45, loss=0.056080, val_loss=0.023339, wait=0/5
cnn/local_unsw/test: epoch 43/45, loss=0.055141, val_loss=0.022983, wait=0/5
cnn/local_unsw/test: epoch 44/45, loss=0.055395, val_loss=0.022719, wait=0/5
cnn/local_unsw/test: epoch 45/45, loss=0.054496, val_loss=0.022488, wait=0/5
RESTORE cnn/local_unsw: epoch 45 with minimum val_loss; no refit.
cnn/local_bot/test: epoch 1/45, loss=0.500567, val_loss=0.413356, wait=0/5
cnn/local_bot/test: epoch 2/45, loss=0.303795, val_loss=0.282554, wait=0/5
cnn/local_bot/test: epoch 3/45, loss=0.223899, val_loss=0.216356, wait=0/5
cnn/local_bot/test: epoch 4/45, loss=0.190165, val_loss=0.175209, wait=0/5
cnn/local_bot/test: epoch 5/45, loss=0.169299, val_loss=0.153125, wait=0/5
cnn/local_bot/test: epoch 6/45, loss=0.154045, val_loss=0.137655, wait=0/5
cnn/local_bot/test: epoch 7/45, loss=0.143162, val_loss=0.133232, wait=0/5
cnn/local_bot/test: epoch 8/45, loss=0.136110, val_loss=0.130998, wait=0/5
cnn/local_bot/test: epoch 9/45, loss=0.130906, val_loss=0.135716, wait=1/5
cnn/local_bot/test: epoch 10/45, loss=0.125617, val_loss=0.139780, wait=2/5
cnn/local_bot/test: epoch 11/45, loss=0.121137, val_loss=0.142732, wait=3/5
cnn/local_bot/test: epoch 12/45, loss=0.117570, val_loss=0.150026, wait=4/5
cnn/local_bot/test: epoch 13/45, loss=0.112788, val_loss=0.151202, wait=5/5
EARLY STOP cnn/local_bot: 5 epochs without val_loss improvement; no refit.
RESTORE cnn/local_bot: epoch 8 with minimum val_loss; no refit.
cnn/local_cic/test: epoch 1/45, loss=0.374414, val_loss=0.158417, wait=0/5
cnn/local_cic/test: epoch 2/45, loss=0.217604, val_loss=0.123323, wait=0/5
cnn/local_cic/test: epoch 3/45, loss=0.191001, val_loss=0.111791, wait=0/5
cnn/local_cic/test: epoch 4/45, loss=0.173407, val_loss=0.104751, wait=0/5
cnn/local_cic/test: epoch 5/45, loss=0.162530, val_loss=0.099834, wait=0/5
cnn/local_cic/test: epoch 6/45, loss=0.154125, val_loss=0.096519, wait=0/5
cnn/local_cic/test: epoch 7/45, loss=0.148071, val_loss=0.095402, wait=0/5
cnn/local_cic/test: epoch 8/45, loss=0.145242, val_loss=0.093602, wait=0/5
cnn/local_cic/test: epoch 9/45, loss=0.141345, val_loss=0.091976, wait=0/5
cnn/local_cic/test: epoch 10/45, loss=0.139071, val_loss=0.091518, wait=0/5
cnn/local_cic/test: epoch 11/45, loss=0.137310, val_loss=0.091014, wait=0/5
cnn/local_cic/test: epoch 12/45, loss=0.135142, val_loss=0.090541, wait=0/5
cnn/local_cic/test: epoch 13/45, loss=0.134388, val_loss=0.089562, wait=0/5
cnn/local_cic/test: epoch 14/45, loss=0.133710, val_loss=0.088959, wait=0/5
cnn/local_cic/test: epoch 15/45, loss=0.132433, val_loss=0.089294, wait=1/5
cnn/local_cic/test: epoch 16/45, loss=0.132428, val_loss=0.088574, wait=0/5
cnn/local_cic/test: epoch 17/45, loss=0.131107, val_loss=0.088507, wait=0/5
cnn/local_cic/test: epoch 18/45, loss=0.130818, val_loss=0.088313, wait=0/5
cnn/local_cic/test: epoch 19/45, loss=0.130603, val_loss=0.087723, wait=0/5
cnn/local_cic/test: epoch 20/45, loss=0.129322, val_loss=0.088077, wait=1/5
cnn/local_cic/test: epoch 21/45, loss=0.129712, val_loss=0.087384, wait=0/5
cnn/local_cic/test: epoch 22/45, loss=0.128845, val_loss=0.087108, wait=0/5
cnn/local_cic/test: epoch 23/45, loss=0.128419, val_loss=0.086683, wait=0/5
cnn/local_cic/test: epoch 24/45, loss=0.128502, val_loss=0.086783, wait=1/5
cnn/local_cic/test: epoch 25/45, loss=0.128054, val_loss=0.086478, wait=0/5
cnn/local_cic/test: epoch 26/45, loss=0.127461, val_loss=0.086278, wait=0/5
cnn/local_cic/test: epoch 27/45, loss=0.127743, val_loss=0.086383, wait=1/5
cnn/local_cic/test: epoch 28/45, loss=0.126846, val_loss=0.086446, wait=2/5
cnn/local_cic/test: epoch 29/45, loss=0.126686, val_loss=0.086196, wait=0/5
cnn/local_cic/test: epoch 30/45, loss=0.126371, val_loss=0.085937, wait=0/5
cnn/local_cic/test: epoch 31/45, loss=0.126097, val_loss=0.085862, wait=0/5
cnn/local_cic/test: epoch 32/45, loss=0.125971, val_loss=0.085502, wait=0/5
cnn/local_cic/test: epoch 33/45, loss=0.125431, val_loss=0.085863, wait=1/5
cnn/local_cic/test: epoch 34/45, loss=0.125596, val_loss=0.085222, wait=0/5
cnn/local_cic/test: epoch 35/45, loss=0.125640, val_loss=0.085661, wait=1/5
cnn/local_cic/test: epoch 36/45, loss=0.124457, val_loss=0.085137, wait=0/5
cnn/local_cic/test: epoch 37/45, loss=0.124712, val_loss=0.085137, wait=0/5
cnn/local_cic/test: epoch 38/45, loss=0.124396, val_loss=0.085263, wait=1/5
cnn/local_cic/test: epoch 39/45, loss=0.124631, val_loss=0.085153, wait=2/5
cnn/local_cic/test: epoch 40/45, loss=0.124253, val_loss=0.084936, wait=0/5
cnn/local_cic/test: epoch 41/45, loss=0.124037, val_loss=0.084999, wait=1/5
cnn/local_cic/test: epoch 42/45, loss=0.123883, val_loss=0.085003, wait=2/5
cnn/local_cic/test: epoch 43/45, loss=0.124049, val_loss=0.084818, wait=0/5
cnn/local_cic/test: epoch 44/45, loss=0.123525, val_loss=0.084853, wait=1/5
cnn/local_cic/test: epoch 45/45, loss=0.122878, val_loss=0.084507, wait=0/5
RESTORE cnn/local_cic: epoch 45 with minimum val_loss; no refit.
cnn/centralized/test: epoch 1/45, loss=0.368915, val_loss=0.211674, wait=0/5
cnn/centralized/test: epoch 2/45, loss=0.238857, val_loss=0.189177, wait=0/5
cnn/centralized/test: epoch 3/45, loss=0.209735, val_loss=0.170925, wait=0/5
cnn/centralized/test: epoch 4/45, loss=0.190528, val_loss=0.155958, wait=0/5
cnn/centralized/test: epoch 5/45, loss=0.177321, val_loss=0.145239, wait=0/5
cnn/centralized/test: epoch 6/45, loss=0.168388, val_loss=0.137557, wait=0/5
cnn/centralized/test: epoch 7/45, loss=0.161866, val_loss=0.135621, wait=0/5
cnn/centralized/test: epoch 8/45, loss=0.156866, val_loss=0.132364, wait=0/5
cnn/centralized/test: epoch 9/45, loss=0.152955, val_loss=0.132111, wait=0/5
cnn/centralized/test: epoch 10/45, loss=0.150765, val_loss=0.130609, wait=0/5
cnn/centralized/test: epoch 11/45, loss=0.148305, val_loss=0.130442, wait=0/5
cnn/centralized/test: epoch 12/45, loss=0.146199, val_loss=0.128960, wait=0/5
cnn/centralized/test: epoch 13/45, loss=0.144108, val_loss=0.125308, wait=0/5
cnn/centralized/test: epoch 14/45, loss=0.142649, val_loss=0.124407, wait=0/5
cnn/centralized/test: epoch 15/45, loss=0.141633, val_loss=0.123762, wait=0/5
cnn/centralized/test: epoch 16/45, loss=0.140132, val_loss=0.122260, wait=0/5
cnn/centralized/test: epoch 17/45, loss=0.139166, val_loss=0.123418, wait=1/5
cnn/centralized/test: epoch 18/45, loss=0.137768, val_loss=0.118871, wait=0/5
cnn/centralized/test: epoch 19/45, loss=0.137078, val_loss=0.118266, wait=0/5
cnn/centralized/test: epoch 20/45, loss=0.136211, val_loss=0.117506, wait=0/5
cnn/centralized/test: epoch 21/45, loss=0.134850, val_loss=0.114510, wait=0/5
cnn/centralized/test: epoch 22/45, loss=0.133934, val_loss=0.112475, wait=0/5
cnn/centralized/test: epoch 23/45, loss=0.131916, val_loss=0.113468, wait=1/5
cnn/centralized/test: epoch 24/45, loss=0.131652, val_loss=0.112354, wait=0/5
cnn/centralized/test: epoch 25/45, loss=0.130907, val_loss=0.111318, wait=0/5
cnn/centralized/test: epoch 26/45, loss=0.130291, val_loss=0.111602, wait=1/5
cnn/centralized/test: epoch 27/45, loss=0.130265, val_loss=0.111999, wait=2/5
cnn/centralized/test: epoch 28/45, loss=0.128945, val_loss=0.112756, wait=3/5
cnn/centralized/test: epoch 29/45, loss=0.128554, val_loss=0.111606, wait=4/5
cnn/centralized/test: epoch 30/45, loss=0.128303, val_loss=0.111454, wait=5/5
EARLY STOP cnn/centralized: 5 epochs without val_loss improvement; no refit.
RESTORE cnn/centralized: epoch 25 with minimum val_loss; no refit.
cnn/federated/test: round 1/15 | test reserved for final round
cnn/federated/test: round 2/15 | test reserved for final round
cnn/federated/test: round 3/15 | test reserved for final round
cnn/federated/test: round 4/15 | test reserved for final round
cnn/federated/test: round 5/15 | test reserved for final round
cnn/federated/test: round 6/15 | test reserved for final round
cnn/federated/test: round 7/15 | test reserved for final round
cnn/federated/test: round 8/15 | test reserved for final round
cnn/federated/test: round 9/15 | test reserved for final round
cnn/federated/test: round 10/15 | test reserved for final round
cnn/federated/test: round 11/15 | test reserved for final round
cnn/federated/test: round 12/15 | test reserved for final round
cnn/federated/test: round 13/15 | test reserved for final round
cnn/federated/test: round 14/15 | test reserved for final round
cnn/federated/test: round 15/15 | test reserved for final round

,model,scenario,source,test_dataset,samples,accuracy,precision,recall,f1,far,auc,tn,fp,fn,tp
0,cnn,centralized,all_clients,unsw,57032,0.993249,0.990891,0.995652,0.993266,0.009153,0.997178,28255,261,124,28392
1,cnn,centralized,all_clients,bot,81023,0.971860,0.995850,0.947669,0.971162,0.003949,0.993564,40352,160,2120,38391
2,cnn,centralized,all_clients,cic,300000,0.976007,0.995084,0.956740,0.975535,0.004727,0.986387,149291,709,6489,143511
3,cnn,federated,all_clients,unsw,57032,0.907052,0.937112,0.872668,0.903742,0.058564,0.966969,26846,1670,3631,24885
4,cnn,federated,all_clients,bot,81023,0.924762,0.917303,0.933697,0.925428,0.084173,0.967133,37102,3410,2686,37825
5,cnn,federated,all_clients,cic,300000,0.879730,0.873738,0.887747,0.880686,0.128287,0.955374,130757,19243,16838,133162
6,cnn,local,bot,unsw,57032,0.819487,0.882200,0.737446,0.803354,0.098471,0.872799,25708,2808,7487,21029
7,cnn,local,bot,bot,81023,0.967540,0.994053,0.940707,0.966645,0.005628,0.997784,40284,228,2402,38109
8,cnn,local,bot,cic,300000,0.780823,0.858580,0.672400,0.754170,0.110753,0.781304,133387,16613,49140,100860
9,cnn,local,cic,unsw,57032,0.478661,0.475938,0.422079,0.447393,0.464757,0.464346,15263,13253,16480,12036
10,cnn,local,cic,bot,81023,0.647952,0.592067,0.951421,0.729912,0.655509,0.798522,13956,26556,1968,38543
11,cnn,local,cic,cic,300000,0.977847,0.997619,0.957980,0.977398,0.002287,0.987763,149657,343,6303,143697
12,cnn,local,unsw,unsw,57032,0.995283,0.991303,0.999334,0.995302,0.008767,0.998226,28266,250,19,28497
13,cnn,local,unsw,bot,81023,0.832208,0.770154,0.947051,0.849491,0.282632,0.812513,29062,11450,2145,38366
14,cnn,local,unsw,cic,300000,0.682323,0.615130,0.974140,0.754085,0.609493,0.631288,58576,91424,3879,146121
15,dnn,centralized,all_clients,unsw,57032,0.991741,0.989869,0.993653,0.991757,0.010170,0.995116,28226,290,181,28335
16,dnn,centralized,all_clients,bot,81023,0.965553,0.997914,0.933055,0.964396,0.001950,0.994791,40433,79,2712,37799
17,dnn,centralized,all_clients,cic,300000,0.976873,0.997213,0.956420,0.976390,0.002673,0.985847,149599,401,6537,143463
18,dnn,federated,all_clients,unsw,57032,0.842299,0.925427,0.744600,0.825223,0.060001,0.906755,26805,1711,7283,21233
19,dnn,federated,all_clients,bot,81023,0.954605,0.978289,0.929846,0.953452,0.020636,0.979922,39676,836,2842,37669
20,dnn,federated,all_clients,cic,300000,0.900773,0.892392,0.911453,0.901822,0.109907,0.943370,133514,16486,13282,136718
21,dnn,local,bot,unsw,57032,0.844035,0.865096,0.815191,0.839403,0.127122,0.891705,24891,3625,5270,23246
22,dnn,local,bot,bot,81023,0.968996,0.995359,0.942386,0.968149,0.004394,0.996686,40334,178,2334,38177
23,dnn,local,bot,cic,300000,0.726177,0.726205,0.726113,0.726159,0.273760,0.656884,108936,41064,41083,108917
24,dnn,local,cic,unsw,57032,0.476890,0.471373,0.380523,0.421104,0.426743,0.445846,16347,12169,17665,10851
25,dnn,local,cic,bot,81023,0.378929,0.363241,0.321592,0.341150,0.563734,0.399319,17674,22838,27483,13028
26,dnn,local,cic,cic,300000,0.971853,0.986955,0.956347,0.971410,0.012640,0.981765,148104,1896,6548,143452
27,dnn,local,unsw,unsw,57032,0.996283,0.993170,0.999439,0.996294,0.006873,0.998339,28320,196,16,28500
28,dnn,local,unsw,bot,81023,0.754921,0.690247,0.924885,0.790523,0.415038,0.826377,23698,16814,3043,37468
29,dnn,local,unsw,cic,300000,0.617213,0.573190,0.917960,0.705718,0.683533,0.544399,47470,102530,12306,137694
30,lstm,centralized,all_clients,unsw,57032,0.996879,0.994762,0.999018,0.996886,0.005260,0.998623,28366,150,28,28488
31,lstm,centralized,all_clients,bot,81023,0.993533,0.999550,0.987510,0.993493,0.000444,0.997376,40494,18,506,40005
32,lstm,centralized,all_clients,cic,300000,0.978300,0.998957,0.957600,0.977841,0.001000,0.986000,149850,150,6360,143640
33,lstm,federated,all_clients,unsw,57032,0.818523,0.960552,0.664329,0.785439,0.027283,0.962163,27738,778,9572,18944
34,lstm,federated,all_clients,bot,81023,0.955605,0.958513,0.952433,0.955463,0.041222,0.991393,38842,1670,1927,38584
35,lstm,federated,all_clients,cic,300000,0.924247,0.951480,0.894087,0.921891,0.045593,0.952348,143161,6839,15887,134113
36,lstm,local,bot,unsw,57032,0.786436,0.786939,0.785559,0.786248,0.212688,0.863079,22451,6065,6115,22401
37,lstm,local,bot,bot,81023,0.975254,0.997854,0.952556,0.974679,0.002049,0.994733,40429,83,1922,38589
38,lstm,local,bot,cic,300000,0.658193,0.646109,0.699547,0.671767,0.383160,0.743613,92526,57474,45068,104932
39,lstm,local,cic,unsw,57032,0.437404,0.384928,0.209391,0.271236,0.334584,0.267473,18975,9541,22545,5971
40,lstm,local,cic,bot,81023,0.351147,0.253344,0.152897,0.190702,0.450607,0.210427,22257,18255,34317,6194
41,lstm,local,cic,cic,300000,0.979777,0.999479,0.960053,0.979370,0.000500,0.988928,149925,75,5992,144008
42,lstm,local,unsw,unsw,57032,0.996563,0.993277,0.999895,0.996575,0.006768,0.996300,28323,193,3,28513
43,lstm,local,unsw,bot,81023,0.866680,0.824256,0.932093,0.874864,0.198731,0.885996,32461,8051,2751,37760
44,lstm,local,unsw,cic,300000,0.676513,0.613943,0.951080,0.746199,0.598053,0.674283,60292,89708,7338,142662